### PR TITLE
Create CNAME

### PR DESCRIPTION
**Pull request by fniephaus**

### CODE REVIEW

**Comment by shaunlebron** [comment]
hey thanks, this is surprising.  I actually removed the CNAME recently because I was tired of all my gh-pages branches redirecting to my domain.  I couldn't opt-out for the branches I didn't want.

You might've tried to reach a link that used to link to shaunlebron.com.  Which one was that?

**Comment by fniephaus** [comment]
The one in this very repository. Check the README.md :)

**Comment by shaunlebron** [comment]
lol, thanks

**Comment by fniephaus** [comment]
What exactly did you mean by "all the gh-pages branches"?
The ones from other repositories? I wonder what happens if a CNAME file links to let's say google.com

**Comment by shaunlebron** [comment]
Yeah, gh-pages from every github repo in your account becomes redirected to the domain name in CNAME.

You have to set your DNS server on your domain to point to github's, If CNAME is set to google.com, github would never get a chance to resolve it because google's dns doesn't point to github.  I don't really understand this stuff though.

**Comment by fniephaus** [comment]
Hi @shaunlebron, I believe that should still be possible.

What exactly are you trying to achieve? Something like this?
`shaunlebron.github.io` -> shaunlebron.com (CNAME with `shaunlebron.com`)
`bl1nd-ld28` -> shaunlebron.github.io/bl1nd-ld28 (CNAME with `shaunlebron.github.io`)

Check this out: 
https://help.github.com/articles/user-organization-and-project-pages/#project-pages
> If no custom domain is used, the Project Pages sites are served under a subpath of the User Pages site: username.github.io/projectname
> A custom domain on User and Organization Pages sites applies the same domain redirect to all Project Pages sites hosted under that account. Project Pages sites that use a custom domain are also available at username.github.io/projectname for personal accounts, and orgname.github.io/projectname for organizations.

**Comment by shaunlebron** [comment]
Yeah, that's what I was going for originally.  Thanks a lot, didn't know I could just dump a CNAME into a project to override the default.

**Comment by fniephaus** [comment]
No worries. Happy to help. :)

**Pull request closed without merging**
